### PR TITLE
Flyte node timeout is an usererror

### PR DESCRIPTION
**Pull request by surindersinghp**
# TL;DR
Node timeout error should be tagged as an user error

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
https://github.com/lyft/flyte/issues/277

### CODE REVIEW

**Comment by kumare3** [comment]
How did this improve coverage?

**Comment by EngHabu** [comment]
Unit test?

**Comment by EngHabu** [comment]
@kumare3 probably because this line was already being covered in a test, and since we increased the size of the block, it looked like more code (percentage) is covered

**Comment by surindersinghp** [comment]
How did this improve coverage?
>> the line was already covered, and has been split from 1 into 2 :)

**Pull request merged**
